In [1]:
import scanpy as sc
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
from tqdm import tqdm
from sklearn import preprocessing

## CITE seq

In [2]:
# Read the healthy citeseq dataset 
healthy_codex_cite = sc.read_h5ad("/home/icb/alessandro.palma/environment/scportrait_ot/project_folder/data/codex/citeseq/cellfeaturization_results_healthy_processed.h5ad")
tonsilitis_codex_cite = sc.read_h5ad("/home/icb/alessandro.palma/environment/scportrait_ot/project_folder/data/codex/citeseq/cellfeaturization_results_tonsilitis_processed.h5ad")

Scale the features

In [3]:
scaler = preprocessing.StandardScaler()
healthy_codex_cite.X = scaler.fit_transform(healthy_codex_cite.X)
healthy_codex_cite.X

array([[-1.0874388 , -3.046413  , -0.92486566, ..., -1.2126375 ,
        -2.4383569 , -0.8761074 ],
       [-0.8963065 , -2.01362   , -0.37918943, ..., -0.5467276 ,
        -1.0255988 , -0.44730237],
       [-0.8613775 , -1.8419701 , -0.8103915 , ..., -0.24657801,
        -1.3101273 ,  0.04025251],
       ...,
       [-0.9048315 , -1.7465267 , -0.7572166 , ..., -1.189934  ,
        -1.766531  , -0.45462698],
       [-0.8749196 , -1.9343331 , -0.72375256, ..., -1.2660115 ,
        -2.1281033 , -0.2599198 ],
       [-1.0275111 , -2.3109984 , -0.94315714, ..., -1.3219851 ,
        -2.2932289 , -0.6329917 ]], dtype=float32)

In [4]:
scaler = preprocessing.StandardScaler()
tonsilitis_codex_cite.X = scaler.fit_transform(tonsilitis_codex_cite.X)
tonsilitis_codex_cite.X

array([[-0.19833429,  0.07003807, -0.15343954, ..., -0.14249988,
        -0.09922125,  0.790859  ],
       [-0.35503605, -0.61790895,  0.13720253, ..., -0.56700057,
        -0.8516759 , -0.10697756],
       [-0.83229214, -1.4575107 , -0.9057591 , ..., -0.7915901 ,
        -1.2518826 , -0.9404921 ],
       ...,
       [-1.04803   , -1.4431874 , -1.0732057 , ..., -0.89116234,
        -1.3545104 , -0.4617932 ],
       [-0.78646445, -0.9560645 , -0.6562339 , ..., -0.65310097,
        -0.5761328 , -0.3932631 ],
       [-0.58257365, -0.02194658, -0.6678434 , ...,  0.04630184,
         0.21339326,  0.04333021]], dtype=float32)

In [5]:
healthy_codex_cite.write_h5ad("/home/icb/alessandro.palma/environment/scportrait_ot/project_folder/data/codex/citeseq/cellfeaturization_results_healthy_processed_std.h5ad") 
tonsilitis_codex_cite.write_h5ad("/home/icb/alessandro.palma/environment/scportrait_ot/project_folder/data/codex/citeseq/cellfeaturization_results_tonsilitis_std.h5ad")

In [6]:
healthy_codex_cite.X

array([[-1.0874388 , -3.046413  , -0.92486566, ..., -1.2126375 ,
        -2.4383569 , -0.8761074 ],
       [-0.8963065 , -2.01362   , -0.37918943, ..., -0.5467276 ,
        -1.0255988 , -0.44730237],
       [-0.8613775 , -1.8419701 , -0.8103915 , ..., -0.24657801,
        -1.3101273 ,  0.04025251],
       ...,
       [-0.9048315 , -1.7465267 , -0.7572166 , ..., -1.189934  ,
        -1.766531  , -0.45462698],
       [-0.8749196 , -1.9343331 , -0.72375256, ..., -1.2660115 ,
        -2.1281033 , -0.2599198 ],
       [-1.0275111 , -2.3109984 , -0.94315714, ..., -1.3219851 ,
        -2.2932289 , -0.6329917 ]], dtype=float32)

In [7]:
tonsilitis_codex_cite.X

array([[-0.19833429,  0.07003807, -0.15343954, ..., -0.14249988,
        -0.09922125,  0.790859  ],
       [-0.35503605, -0.61790895,  0.13720253, ..., -0.56700057,
        -0.8516759 , -0.10697756],
       [-0.83229214, -1.4575107 , -0.9057591 , ..., -0.7915901 ,
        -1.2518826 , -0.9404921 ],
       ...,
       [-1.04803   , -1.4431874 , -1.0732057 , ..., -0.89116234,
        -1.3545104 , -0.4617932 ],
       [-0.78646445, -0.9560645 , -0.6562339 , ..., -0.65310097,
        -0.5761328 , -0.3932631 ],
       [-0.58257365, -0.02194658, -0.6678434 , ...,  0.04630184,
         0.21339326,  0.04333021]], dtype=float32)